# Generated by Django 5.2.8 on 2025-11-14 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pqr', '0001_initial'),
        ('propiedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pqr',
            name='ciudadano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs_ciudadano', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pqr',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pqr.estadopqr'),
        ),
        migrations.AddField(
            model_name='pqr',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='propiedades.propiedad'),
        ),
        migrations.AddField(
            model_name='pqr',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs_tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pqr',
            name='tipo_falla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pqr.tipofalla'),
        ),
    ]
