# Generated by Django 5.2.8 on 2025-11-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0004_usuarioinsistente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqr',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pqr',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pqr',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pqr',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
